import Link from "next/link";
import styles from "./homepage.module.css";

export default function Home() {
  return <div>
    <Link href="/">
      <h1>Lorem ipsum dolor</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Mollis nunc sed id semper risus in hendrerit gravida. Odio euismod lacinia at quis risus. Dolor purus non enim praesent elementum facilisis leo vel. Augue ut lectus arcu bibendum at varius. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Augue interdum velit euismod in pellentesque. In hac habitasse platea dictumst vestibulum. Laoreet sit amet cursus sit amet dictum sit. Vitae tortor condimentum lacinia quis vel eros. Consectetur adipiscing elit duis tristique sollicitudin nibh sit. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Vitae semper quis lectus nulla at. Egestas quis ipsum suspendisse ultrices. Odio aenean sed adipiscing diam donec adipiscing tristique.Viverra accumsan in nisl nisi. Id eu nisl nunc mi. Lectus sit amet est placerat in egestas erat. Nisi porta lorem mollis aliquam ut porttitor leo. Mauris a diam maecenas sed enim ut sem viverra. Nunc consequat interdum varius sit amet mattis. Dictum non consectetur a erat nam at lectus urna duis. Velit laoreet id donec ultrices tincidunt arcu non. Feugiat pretium nibh ipsum consequat nisl vel pretium. Hendrerit dolor magna eget est. Ut sem viverra aliquet eget sit amet tellus cras. Fermentum posuere urna nec tincidunt praesent. Lorem donec massa sapien faucibus et molestie ac. Fermentum et sollicitudin ac orci phasellus. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Leo vel orci porta non pulvinar. Id diam maecenas ultricies mi. Dui sapien eget mi proin sed libero. Tortor at auctor urna nunc id.Tellus orci ac auctor augue mauris augue neque gravida in. Nullam eget felis eget nunc lobortis mattis aliquam. Posuere sollicitudin aliquam ultrices sagittis orci a. Pellentesque eu tincidunt tortor aliquam. Urna nunc id cursus metus aliquam eleifend mi in nulla. At ultrices mi tempus imperdiet nulla malesuada. Aliquam sem et tortor consequat id porta nibh venenatis cras. Id neque aliquam vestibulum morbi blandit cursus risus at. Et netus et malesuada fames ac turpis egestas integer. Lacus vel facilisis volutpat est velit egestas. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Viverra aliquet eget sit amet tellus. Elit ut aliquam purus sit. Lacinia quis vel eros donec ac. Nec dui nunc mattis enim ut tellus elementum. Urna neque viverra justo nec ultrices dui sapien. Bibendum ut tristique et egestas quis ipsum suspendisse. Cras ornare arcu dui vivamus.</p>
    </Link>
    </div>;
}
