---
title: "Habari Habour Analysis"
author: "Developers"
date: "2024-03-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data

```{r}
library(readxl)
content_creator <- read_excel("07 03 2024 Social Media Information.xlsx")
View(content_creator)
```

## Get the unique Fields

```{r}
unique(content_creator$`Creative industry`)
```

## Visualize the distribution

```{r}
industry_data = data.frame(national_id = content_creator$`National ID`,
                           industry = content_creator$`Creative industry`,
                           count = rep(1, nrow(content_creator)))
```

```{r}
library(dplyr)

industry_data = industry_data %>% group_by(industry) %>% summarise(count = sum(count))

```

```{r}
library(ggplot2)

ggplot(industry_data, aes(x = industry, y = count)) +
  geom_bar(stat = "identity") +
  labs(
    title = "The main fields from the study",
    x = "The creative industry",
    y = "The number of individuals"
  ) +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

# import the specific social media data

```{r}
co_care_treatment = read_excel("Co-Care treatment.xlsx")
colnames(co_care_treatment)
```

## Spliting the social media apps

```{r}
library(stringr)
social_media = c("Facebook", "Instagram", "LinkedIn", "Twitter", "TikTok", "WhatsApp", "YouTube", "Other")
data1 = co_care_treatment

for(platform in social_media){
  data1[[platform]] = as.integer(str_detect(data1$`Social media accounts`, platform))

}

colnames(data1)
```

```{r}
library(tidyr)
social_media_totals <- data1 %>%
  summarise(across(c(Facebook, Instagram, LinkedIn, Twitter, TikTok, WhatsApp, YouTube, Other), sum, na.rm = TRUE)) %>%
  gather(key = "platform", value = "count")


ggplot(social_media_totals, aes(x = "", y = count, fill = platform)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  theme_void() +
  labs(fill = "Platform", title = "Social Media Platform Usage") +
  theme(legend.title = element_text(size = 12), legend.text = element_text(size = 10))
```

## Site data

```{r}
sites = data.frame(region = c("United States International University - Africa", "Kenya Coast National Polytechnic", "Kiambu Institute of Science and Technology","Kisumu YMCA"),
                   count = c(nrow(content_creator[content_creator$`Located Hub` == "United States International University - Africa",]),
                             nrow(content_creator[content_creator$`Located Hub` == "Kenya Coast National Polytechnic" ,]),
                             nrow(content_creator[content_creator$`Located Hub` == "Kiambu Institute of Science and Technology",]),
                             nrow(content_creator[content_creator$`Located Hub` == "Kisumu YMCA",])))

sites
```
